In [1]:
import torch

In [2]:
import numpy as np

In [4]:
torch.__version__

'1.12.0+cpu'

In [5]:
arr=np.array([1,2,3,4,5])

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr.dtype

dtype('int32')

In [8]:
type(arr)

numpy.ndarray

In [9]:
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [10]:
x=torch.from_numpy(arr)

In [11]:
type(x)

torch.Tensor

In [12]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [13]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [14]:
x.dtype

torch.int32

In [15]:
arr2d=np.arange(0.0,12.0)

In [16]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [18]:
arr2d=arr2d.reshape(4,3)

In [19]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [20]:
x2=torch.from_numpy(arr2d)

In [21]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[0]=99

In [24]:
arr

array([99,  2,  3,  4,  5])

In [25]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [26]:
my_arr=np.arange(0,10)

In [27]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_tensor=torch.tensor(my_arr)

In [29]:
my_other_tensor=torch.from_numpy(my_arr)

In [30]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [31]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [32]:
my_arr[0]=999

In [33]:
my_arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [34]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9], dtype=torch.int32)

In [35]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)